<a href="https://colab.research.google.com/github/nidhisharma57350/python/blob/main/Pyhton_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([2,4,5,6])
b=np.array([2,5,6,7])
print(a+b)

[ 4  9 11 13]


In [ ]:
import numpy as np
a=np.arange(1,10,3)
print(a)

[1 4 7]


In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [ ]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.array([[2,4,6,8,10],[3,5,6,7,8]])
print(a.shape)

(2, 5)


In [ ]:
a=np.array([2,4,6])
print(a.shape)

(3,)


In [ ]:
a=np.array([2,3,4,5],[3,2,5])
print(a)

In [ ]:
a=np.array([[2,3,4,5],[6,4,3,2]])
print(a.reshape(4,2))

[[2 3]
 [4 5]
 [6 4]
 [3 2]]


In [ ]:
a=np.array([[2,3,4,5],[6,4,3,2]])
print(a.size)

8


In [ ]:
a=np.array([3,5,6])
print(a.ndim)

1


In [ ]:
import numpy as np
a=np.array([3,5,6])
print(a.dtype)

int64


In [ ]:
a=np.array([4,3,4,5,2])
b=a.astype(float)
print(b)

[4. 3. 4. 5. 2.]


In [ ]:
a=np.array([4,3,4,5,2.5])
print(a.dtype)
b=a.astype(int)
print(b)

float64
[4 3 4 5 2]


In [ ]:
a=np.array([10,20,30,40,50])
print(a**2)
# we can use all other operations in space of +.

[ 100  400  900 1600 2500]


In [ ]:
a=np.array([10,20,30,40,50])
print(a//2)

[ 5 10 15 20 25]


In [ ]:
a=np.array([[3,2,4,5,6,7],[3,4,5,2,3,1]])
print(a*2)

[[ 6  4  8 10 12 14]
 [ 6  8 10  4  6  2]]


In [ ]:
a=np.array([[3,2,4,5,6,7],[3,4,5,2,3,1]])
print(a%2)

[[1 0 0 1 0 1]
 [1 0 1 0 1 1]]


In [ ]:
a=np.array([3,4,5,6,7])
print(a/2)

[1.5 2.  2.5 3.  3.5]


In [ ]:
a=np.array([3,4,5,6,7])
print(a//2)

[1 2 2 3 3]


In [ ]:
a=np.array([2,1,3,4,5,6])
b=np.sum(a)
print(b)
c=np.mean(a)
print(c)
d=np.std(a)
print(d)
g=np.var(a)
print(g)
h=np.max(a)
print(h)
i=np.min(a)
print(i)
j=np.median(a)
print(j)

21
3.5
1.707825127659933
2.9166666666666665
6
1
3.5


In [ ]:
a=np.array([3,2,4,5,4])
b=np.median(a)
print(b)

4.0


In [ ]:
a=np.array([3,2,4,5,6,7,8])
print(a[0])
print(a[2:6])
print(a[::-1])
print(a[::2])
print(a[:])
print(a[::])

3
[4 5 6 7]
[8 7 6 5 4 2 3]
[3 4 6 8]
[3 2 4 5 6 7 8]
[3 2 4 5 6 7 8]


In [ ]:
a=np.array([5,4,3,4,5,6,2,1,9])
print(a[[0,2,5,6]])#Fancy indexing->selecting multiple values at a time by indexing.

[5 3 6 2]


In [ ]:
a=np.array([[[2,5,7,8],[4,3,5,6],[4,5,6,7]]])
print(a.ndim)
print(a.shape)
print(a[0])
print(a[0,2])
print(a[0,-1])

3
(1, 3, 4)
[[2 5 7 8]
 [4 3 5 6]
 [4 5 6 7]]
[4 5 6 7]
[4 5 6 7]


In [ ]:
a=np.array([[[[2,5,7,8],[4,3,5,6],[4,5,6,7]]]])
print(a.ndim)
print(a[0])
print(a[0][0][0,1:])

4
[[[2 5 7 8]
  [4 3 5 6]
  [4 5 6 7]]]
[5 7 8]


In [ ]:
a=np.array([5,4,3,4,5,6])
print(a[a>3])#filtering data/Boolean Masking

[5 4 4 5 6]


In [ ]:
a=np.array([4,5,6,7,8,10,12,5])
print(a.ndim)
b=print(a.reshape(2,4))
c=print(a.reshape(1,8))
d=print(a.reshape(8,1))
e=print(a.reshape(4,2))

1
[[ 4  5  6  7]
 [ 8 10 12  5]]
[[ 4  5  6  7  8 10 12  5]]
[[ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [12]
 [ 5]]
[[ 4  5]
 [ 6  7]
 [ 8 10]
 [12  5]]


In [ ]:
a=np.array([[4,5,6,7],[8,10,12,5]])
print(a)
print(a.ndim)

[[ 4  5  6  7]
 [ 8 10 12  5]]
2


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ravel())# Views, change will occur also in original array.
print(a.flatten())# coppy, change will not occur in original array.

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
a=np.array([4,5,3,6,7,8])
b=np.insert(a,2,10)
print(b)

[ 4  5 10  3  6  7  8]


In [ ]:
a=np.array([[4,5,3,6,7,8]])
b=np.insert(a,2,10,axis=1)
print(b)

[[ 4  5 10  3  6  7  8]]


In [ ]:
a=np.array([[4,5],[3,6],[7,8]])
b=np.insert(a,2,10,axis=0)# axis=0 means adding inserting new row.
print(b)

[[ 4  5]
 [ 3  6]
 [10 10]
 [ 7  8]]


In [ ]:
a=np.array([[4,5],[3,6],[7,8]])
b=np.insert(a,2,10,axis=1)# axis=1 means adding inserting new row.
print(b)

[[ 4  5 10]
 [ 3  6 10]
 [ 7  8 10]]


In [ ]:
a=np.array([[4,5],[3,6],[7,8]])
b=np.insert(a,2,[10,2],axis=0)# axis=1 means adding new column.
print(b)

[[ 4  5]
 [ 3  6]
 [10  2]
 [ 7  8]]


In [ ]:
a=np.array([[4,5],[3,6],[7,8]])
b=np.insert(a,2,[10,2,3],axis=1)# axis=1 means adding new column.
print(b)

[[ 4  5 10]
 [ 3  6  2]
 [ 7  8  3]]


In [ ]:
a=np.array([[4,5],[3,6],[7,8]])
b=np.insert(a,2,[10,2,3],axis=None)# axis=None means inserting elements in flattening(in one single row).
print(b)

[ 4  5 10  2  3  3  6  7  8]


In [ ]:
a=np.array([3,4,5,6,7,8,9])
b=np.append(a,[20])
print(b)
c=np.append(a,[12,13,14,15])
print(c)

[ 3  4  5  6  7  8  9 20]
[ 3  4  5  6  7  8  9 12 13 14 15]


In [ ]:
a=np.array([2,2,3,4,5,6,7,8,10])
b=np.array([2,4,5,5,3,1,8])
c=np.concatenate((a,b))
print(c)

[ 2  2  3  4  5  6  7  8 10  2  4  5  5  3  1  8]


In [ ]:
a=np.array([2,2,3,4,5,6,7,8,10])
b=np.array([2,4,5,5,3,1,2,5,8])
c=np.concatenate((a,b), axis=0)# axis=0 means horizonatal stacking.
print(c)

[ 2  2  3  4  5  6  7  8 10  2  4  5  5  3  1  2  5  8]


In [ ]:
a=np.array([[2,2,3,4,5,6,7,8,10]])
b=np.array([[2,4,5,5,3,1,2,5,8]])
c=np.concatenate((a,b), axis=0)#axis=0 means vertical stacking.
print(c)

[[ 2  2  3  4  5  6  7  8 10]
 [ 2  4  5  5  3  1  2  5  8]]


In [ ]:
a=np.array([3,4,5,2,3,5,6,7])
b=np.delete(a,[2,4])
print(b)

[3 4 2 5 6 7]


In [ ]:
a=np.array([3,4,5,2,3,5,6,7])
b=np.delete(a,[2,4,5])
print(b)

[3 4 2 6 7]


In [ ]:
a=np.array([[3,4,5,2,3,5,6,7]])
b=np.delete(a,[2,4,5])
print(b)

[3 4 2 6 7]


In [ ]:
a=np.array([[2,3,4,5],[3,2,5,6]])
b=np.delete(a,1,axis=0)
print(b)

[[2 3 4 5]]


In [ ]:
a=np.array([[2,3,4,5],[3,2,5,6]])
b=np.delete(a,1,axis=1)
print(b)

[[2 4 5]
 [3 5 6]]


In [ ]:
a=np.array([3,2,4,5])
b=np.array([2,1,9,2])
print(np.vstack((a,b)))# vertically stack.

[[3 2 4 5]
 [2 1 9 2]]


In [ ]:
a=np.array([3,2,4,5])
b=np.array([2,1,9,2])
print(np.hstack((a,b)))# horizontally stack.

[3 2 4 5 2 1 9 2]


In [ ]:
a=np.array([10,20,30,40,10,30])
print(np.split(a,3))

[array([10, 20]), array([30, 40]), array([10, 30])]


In [ ]:
a=np.array([[10,20,30],[40,10,30]])
print(np.hsplit(a,3))

[array([[10],
       [40]]), array([[20],
       [10]]), array([[30],
       [30]])]


In [ ]:
a=np.array([[10,20,30],[40,10,30]])
print(np.vsplit(a,2))

[array([[10, 20, 30]]), array([[40, 10, 30]])]
