<a href="https://colab.research.google.com/github/nidhisharma57350/python/blob/main/Python_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1,5,8,9,10,5,8,8,9,5,4,6]
print(set(a))

{1, 4, 5, 6, 8, 9, 10}


In [ ]:
set:
a = {8,6,5,4,3,2,9}
b = {2,1,0,5,4,6}
c = a.union(b)
print("a union b : ",c)

d = a.intersection(b)
print("a intersection b :",d)

e = a.difference(b)
print("a - b :",e)

f = a.symmetric_difference(b)
print("symmetric difference of a and b :",f)

In [ ]:
a = ["nidhi","kaku","sharma","titu"]
b = [50,55,35,67]
c = zip(a,b)
print(c)

In [ ]:
a = ["nidhi","kaku","nidhi","titu"]
b = [50,55,35,67]
c = dict(zip(a,b)) # we can also use dict.
print(c)

In [ ]:
a = ["nidhi","kaku","sharma","titu"]
b = [50,55,35,67]
c = tuple(zip(a,b)) # we can also use dict.
print(c)

In [ ]:
a = ["nidhi","kaku","nidhi","titu"]
b = [50,55,50,67]
c = set(zip(a,b)) # we can also use dict.
print(c)

In [ ]:
def average(list):
  return sum(list)/len(list)
print(average([2,3,4,5,6,7,8]))

# Dictionary:

In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "course": "Data Science"
}
print(student)

print("student's name is",student["name"])
print("student's course is",student["course"])
print("student's age is",student["age"])

{'name': 'Nidhi', 'age': 23, 'course': 'Data Science'}
student's name is Nidhi
student's course is Data Science
student's age is 23


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23
}

student["city"] = "Chandigarh"

print(student)

{'name': 'Nidhi', 'age': 23, 'city': 'Chandigarh'}


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23
}

student["age"] = 24
print(student)

{'name': 'Nidhi', 'age': 24}


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "city": "Chandigarh"
}

del student["age"]

print(student)

{'name': 'Nidhi', 'city': 'Chandigarh'}


In [ ]:
# get() method:
student = {
    "name": "Nidhi",
    "age": 23
}

print(student.get("name"))
print(student.get("city"))

Nidhi
None


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "course": "Data Science"
}

print(student.keys())

dict_keys(['name', 'age', 'course'])


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "course": "Data Science"
}
print(student.values())

dict_values(['Nidhi', 23, 'Data Science'])


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "course": "Data Science"
}

print(student.items())

dict_items([('name', 'Nidhi'), ('age', 23), ('course', 'Data Science')])


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "course": "Data Science"
}

for key, value in student.items():
    print(key, ":", value)

name : Nidhi
age : 23
course : Data Science


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23
}

if "name" in student:
    print("Name is present")
else:
    print("Name is not present")

Name is present


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "city": "Chandigarh"
}

student.pop("age")

print(student)

{'name': 'Nidhi', 'city': 'Chandigarh'}


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23
}

student.update({"city": "Chandigarh", "course": "Data Science"})

print(student)

{'name': 'Nidhi', 'age': 23, 'city': 'Chandigarh', 'course': 'Data Science'}


In [ ]:
student = {
    "name": "Nidhi",
    "age": 23,
    "course": "Data Science"
}

print(len(student))

3


In [ ]:
marks = {
    "Python": 85,
    "SQL": 90,
    "Machine Learning": 88
}

print("Python Marks:", marks["Python"])

marks["Python"] = 92

print("Updated Marks:", marks["Python"])

Python Marks: 85
Updated Marks: 92


In [ ]:
import numpy as np
x=np.array([5,6,7])
print(x)

In [ ]:
x=[5,6,7],[6,8,4]
y=[5,2,3]
x[0]
print(x[0])
x[0][1]
print(x[0][1])
x=np.array([5,6,7]),([6,8,4])
y=np.array([5,2,3])
z=x+y
print(z)
x=np.array([5,6,7]),([6,8,4])
y=np.array([5])
p=x+y
print(p)

[5, 6, 7]
6
[[10  8 10]
 [11 10  7]]
[[10 11 12]
 [11 13  9]]


In [ ]:
import pandas as pd
employees={"names":["nidhi","sunidhi","priya"],
"ages":[22,23,24],
"salaries":[100000,90000,95000]}
df=pd.DataFrame(employees)
print(df)

     names  ages  salaries
0    nidhi    22    100000
1  sunidhi    23     90000
2    priya    24     95000


In [ ]:
import numpy as np
x=np.array([4,6,8]),([2,4,6])
y=np.array([5])
z=x+y
print(z)

[[ 9 11 13]
 [ 7  9 11]]


In [ ]:
import pandas as pd
employee={"names":["nidhi","neha",None,"shikha","radha"],
"ages":[22,23,24,None,26],
"salary":[30000,40000,None,50000,60000]}
df=pd.DataFrame(employee)
df.info()
df.columns
df.dtypes
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   names   4 non-null      object 
 1   ages    4 non-null      float64
 2   salary  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes
    names  ages   salary
0   nidhi  22.0  30000.0
1    neha  23.0  40000.0
2    None  24.0      NaN
3  shikha   NaN  50000.0
4   radha  26.0  60000.0


In [ ]:
import pandas as pd
employee={"names":["nidhi","sunidhi",None,"neha","sneha"],
"ages":[22,23,24,None,25],
"salary":[50000,60000,None,60000,65000]}
df.fillna({"names":"unknown","salary":df["salary"].mean(),"ages":df["ages"].mean()})


,names,ages,salary
0,nidhi,22.00,30000.0
1,neha,23.00,40000.0
2,unknown,24.00,45000.0
3,shikha,23.75,50000.0
4,radha,26.00,60000.0
